### ISSUE TITLE
How does this package differ from envrc?

### ISSUE THREAD

**Issue by bbigras** [amodelbello/dot-env.el#1]
https://github.com/purcell/envrc

**Comment by amodelbello** [comment]
It's a different use case. The envrc package looks to me to be a tool to manage environment variables on a per-project basis. dot-env is a package that manages _Emacs_ specific environment variables to aid in using the same Emacs config across different machines and environments.

**Comment by bbigras** [comment]
Ok, so one .env per emacs (yours), vs 1 .env file per folder (envrc). Thanks!
